include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
  errors:
    lines_longer_than_80_chars: ignore

linter:
  rules:
  - avoid_bool_literals_in_conditional_expressions
  - comment_references
  - directives_ordering
  - no_leading_underscores_for_local_identifiers
  - omit_local_variable_types
  - prefer_final_in_for_each
  - prefer_final_locals
  - prefer_relative_imports
  - use_super_parameters
