include: package:lints/recommended.yaml

linter:
  rules:
    comment_references: true
    directives_ordering: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    prefer_spread_collections: false
