include: package:pedantic/analysis_options.1.9.0.yaml

analyzer:
  strong-mode:
    implicit-casts: false

linter:
  rules:
    camel_case_types: true
    control_flow_in_finally: true
    directives_ordering: true
    prefer_single_quotes: false # will be fixed later
    throw_in_finally: true
